---
AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket for SageMaker
Parameters:
  ProjectName:
    Description: Set the project name.
    Type: String
    Default: ml
Resources:
  SageMakerS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub ${ProjectName}-sagemaker-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: Move-to-Intelligent-Tiering-after-0day
            Status: Enabled
            Transitions:
              - TransitionInDays: 0
                StorageClass: INTELLIGENT_TIERING
            NoncurrentVersionExpiration:
              NoncurrentDays: 7
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-sagemaker-${AWS::AccountId}
        - Key: ProjectName
          Value: !Ref ProjectName
Outputs:
  SageMakerS3Bucket:
    Description: S3 bucket for SageMaker
    Value: !Ref SageMakerS3Bucket
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-SageMakerS3Bucket
