---
AWSTemplateFormatVersion: 2010-09-09
Description: SageMaker Studio user profile
Parameters:
  ProjectName:
    Description: Set the project name.
    Type: String
    Default: ml
  SageMakerStudioDomainStackName:
    Description: Set the SageMaker Studio domain stack name.
    Type: String
    Default: sagemaker-studio-domain
  IamStackName:
    Description: Set the IAM stack name.
    Type: String
    Default: iam-roles-for-sagemaker
Resources:
  SageMakerStudioUserProfile:
    Type: AWS::SageMaker::UserProfile
    Properties:
      UserProfileName: !Sub ${ProjectName}-sagemaker-user-profile
      UserSettings:
        ExecutionRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-SageMakerExecutionRole
      DomainId:
        Fn::ImportValue: !Sub ${AWS::Region}-${SageMakerStudioDomainStackName}-SageMakerStudioDomain
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-sagemaker-user-profile
        - Key: ProjectName
          Value: !Ref ProjectName
Outputs:
  SageMakerStudioUserProfile:
    Description: SageMaker Studio user profile
    Value: !Ref SageMakerStudioUserProfile
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-SageMakerStudioUserProfile
