---
AWSTemplateFormatVersion: 2010-09-09
Description: SageMaker Studio domain
Parameters:
  ProjectName:
    Description: Set the project name.
    Type: String
    Default: ml
  VpcStackName:
    Description: Set the VPC stack name.
    Type: String
    Default: vpc-private-subnets-and-endpoints
  IamStackName:
    Description: Set the IAM stack name.
    Type: String
    Default: iam-roles-for-sagemaker
Resources:
  SageMakerStudioDomain:
    Type: AWS::SageMaker::Domain
    Properties:
      DomainName: !Sub ${ProjectName}-sagemaker-studio-domain
      DefaultUserSettings:
        ExecutionRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-SageMakerExecutionRole
      VpcId:
        Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-Vpc
      SubnetIds:
        - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
        - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
        - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
      AppNetworkAccessType: PublicInternetOnly
      AuthMode: IAM
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-sagemaker-studio-domain
        - Key: ProjectName
          Value: !Ref ProjectName
Outputs:
  SageMakerStudioDomainId:
    Description: SageMaker Studio domain Id
    Value: !GetAtt SageMakerStudioDomain.DomainId
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-SageMakerStudioDomain
